import {hashSync} from 'bcrypt-ts-edge';

const sampleData = {
  users: [
    {
      name: 'John Doe',
      email: 'admin@example.com',
      password: hashSync('123456', 10),
      role: 'admin',
      createdBy: 'system',
    },
    {
      name: 'Jane Doe',
      email: 'user@example.com',
      password: hashSync('123456', 10),
      role: 'user',
      createdBy: 'system',
    },
  ],
  products: [
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      sku: 'MDS-POLO-LB-S',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 899000,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      size: 'S',
      color: 'LIGHT BLUE',
      banner: 'banner-1.jpg',
      createdBy: 'system',
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      sku: 'MDS-BROOK-BRO-M',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 1399000,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      size: 'M',
      color: 'BROWN',
      banner: 'banner-2.jpg',
      createdBy: 'system',
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      sku: 'MDS-TOMMY-LY-M',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 1649000,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      size: 'M',
      color: 'LIGHT YELLOW',
      isFeatured: false,
      banner: null,
      createdBy: 'system',
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      sku: 'MDS-CALVI-DB-L',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 649000,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      size: 'L',
      color: 'DARK BROWN',
      banner: null,
      createdBy: 'system',
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      sku: 'MDS-POLO-BLU-L',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 1299000,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      size: 'L',
      color: 'BLUE',
      banner: null,
      createdBy: 'system',
    },
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      sku: 'MS-POLO-PIN-L',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 1649000,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      size: 'L',
      color: 'PINK',
      banner: null,
      createdBy: 'system',
    },
  ],
};

export {sampleData};
